// Deal-workspace static server (127.0.0.1, port 4318, zero deps). Serves the
// pre-built public/ directory: deal.html, deal-index.json, deal-index.mjs, and
// the per-call receipts pages under public/calls/ — those are generated by
// scripts/build-deal-index.mjs from src/export.js's tier1Html(), so the
// per-call view IS viewer.js, never a reimplementation.
//
// New file, new port: does not touch src/server.js's routes or state.
// Usage: node src/deal-server.mjs [publicDir]
import { createServer } from 'node:http';
import { readFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { extname, join, normalize, sep } from 'node:path';

const HOST = '127.0.0.1';
const PORT = 4318;

export const DEFAULT_PUBLIC_DIR = fileURLToPath(new URL('../public', import.meta.url));

const CONTENT_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.json': 'application/json',
  '.mjs': 'text/javascript; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
};

function fail(res, status, message) {
  if (res.headersSent) {
    res.destroy();
    return;
  }
  res.writeHead(status, { 'Content-Type': 'text/plain' }).end(message);
}

// Resolve a URL path to a file inside publicDir, refusing any traversal
// outside it — a demo server is still a server (same discipline as
// server.js's read-before-headers / never-kill-the-process rules).
export function resolvePath(publicDir, pathname) {
  const decoded = decodeURIComponent(pathname === '/' ? '/deal.html' : pathname);
  const cleaned = normalize(decoded).replace(/^([.][.][/\\])+/, '');
  const full = join(publicDir, cleaned);
  if (full !== publicDir && !full.startsWith(publicDir + sep)) return null;
  return full;
}

export function createApp(publicDir = DEFAULT_PUBLIC_DIR) {
  return (req, res) => {
    try {
      const { pathname } = new URL(req.url, `http://${HOST}`);
      const full = resolvePath(publicDir, pathname);
      if (!full) {
        fail(res, 403, 'forbidden');
        return;
      }
      let stat;
      try {
        stat = statSync(full);
      } catch {
        fail(res, 404, 'not found');
        return;
      }
      if (!stat.isFile()) {
        fail(res, 404, 'not found');
        return;
      }
      const body = readFileSync(full); // read before headers, same as server.js
      const type = CONTENT_TYPES[extname(full)] ?? 'application/octet-stream';
      res.writeHead(200, { 'Content-Type': type, 'Content-Length': body.length }).end(body);
    } catch (err) {
      fail(res, 500, `error: ${err.message}`);
    }
  };
}

export function startServer(publicDir = DEFAULT_PUBLIC_DIR, { host = HOST, port = PORT } = {}) {
  return createServer(createApp(publicDir)).listen(port, host);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const publicDir = process.argv[2] ?? DEFAULT_PUBLIC_DIR;
  startServer(publicDir).on('listening', () => {
    console.log(`deal workspace: http://${HOST}:${PORT}/  (serving ${publicDir})`);
    console.log('run `node scripts/build-deal-index.mjs` first if this is a fresh checkout');
  });
}
