// Deal-workspace static server (127.0.0.1, port 4318, zero deps). Serves the
// pre-built public/ directory: deal.html, deal-index.json, deal-index.mjs, and
// the per-call receipts pages under public/calls/ — those are generated by
// scripts/build-deal-index.mjs from src/export.js's tier1Html(), so the
// per-call view IS viewer.js, never a reimplementation.
//
// New file, new port: does not touch src/server.js's routes or state.
// Usage: node src/deal-server.mjs [publicDir]
import { createServer } from 'node:http';
import { readFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { extname, join, normalize, sep } from 'node:path';

const HOST = '127.0.0.1';
const PORT = 4318;

export const DEFAULT_PUBLIC_DIR = fileURLToPath(new URL('../public', import.meta.url));

const CONTENT_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.json': 'application/json',
  '.mjs': 'text/javascript; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.m4a': 'audio/mp4',
  '.wav': 'audio/wav',
  '.mp3': 'audio/mpeg',
};

function fail(res, status, message) {
  if (res.headersSent) {
    res.destroy();
    return;
  }
  res.writeHead(status, { 'Content-Type': 'text/plain' }).end(message);
}

// Resolve a URL path to a file inside publicDir, refusing any traversal
// outside it — a demo server is still a server (same discipline as
// server.js's read-before-headers / never-kill-the-process rules).
export function resolvePath(publicDir, pathname) {
  const decoded = decodeURIComponent(pathname === '/' ? '/notes/index.html' : pathname);
  const cleaned = normalize(decoded).replace(/^([.][.][/\\])+/, '');
  const full = join(publicDir, cleaned);
  if (full !== publicDir && !full.startsWith(publicDir + sep)) return null;
  return full;
}

// Parse a single-range `Range: bytes=start-end` header against a known size.
// Returns {start, end} (inclusive) or null when absent/unsatisfiable, so a bad
// or multi-range header simply falls back to a whole-file 200 (never throws).
export function parseRange(header, size) {
  if (!header || typeof header !== 'string') return null;
  const m = /^bytes=(\d*)-(\d*)$/.exec(header.trim());
  if (!m) return null;
  const hasStart = m[1] !== '';
  const hasEnd = m[2] !== '';
  let start;
  let end;
  if (hasStart) {
    start = Number(m[1]);
    end = hasEnd ? Number(m[2]) : size - 1;
  } else if (hasEnd) {
    const suffix = Number(m[2]); // last N bytes
    if (suffix === 0) return null;
    start = Math.max(0, size - suffix);
    end = size - 1;
  } else {
    return null;
  }
  end = Math.min(end, size - 1);
  if (!Number.isFinite(start) || !Number.isFinite(end) || start > end || start >= size) return null;
  return { start, end };
}

export function createApp(publicDir = DEFAULT_PUBLIC_DIR) {
  return (req, res) => {
    try {
      const { pathname } = new URL(req.url, `http://${HOST}`);
      const full = resolvePath(publicDir, pathname);
      if (!full) {
        fail(res, 403, 'forbidden');
        return;
      }
      let stat;
      try {
        stat = statSync(full);
      } catch {
        fail(res, 404, 'not found');
        return;
      }
      if (!stat.isFile()) {
        fail(res, 404, 'not found');
        return;
      }
      const body = readFileSync(full); // read before headers, same as server.js
      const type = CONTENT_TYPES[extname(full)] ?? 'application/octet-stream';
      // Range support so the browser can seek audio to a claim's timestamp
      // (the play-from-here reveal). Falls back to a whole-file 200 otherwise.
      const range = parseRange(req.headers.range, body.length);
      if (range) {
        const slice = body.subarray(range.start, range.end + 1);
        res.writeHead(206, {
          'Content-Type': type,
          'Content-Range': `bytes ${range.start}-${range.end}/${body.length}`,
          'Accept-Ranges': 'bytes',
          'Content-Length': slice.length,
        }).end(slice);
        return;
      }
      res.writeHead(200, {
        'Content-Type': type,
        'Content-Length': body.length,
        'Accept-Ranges': 'bytes',
      }).end(body);
    } catch (err) {
      fail(res, 500, `error: ${err.message}`);
    }
  };
}

export function startServer(publicDir = DEFAULT_PUBLIC_DIR, { host = HOST, port = PORT } = {}) {
  return createServer(createApp(publicDir)).listen(port, host);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const publicDir = process.argv[2] ?? DEFAULT_PUBLIC_DIR;
  startServer(publicDir).on('listening', () => {
    console.log(`deal workspace: http://${HOST}:${PORT}/  (serving ${publicDir})`);
    console.log('run `node scripts/build-deal-index.mjs` first if this is a fresh checkout');
  });
}
